export interface WorldCountry {
  name: string;
  code: string; // ISO 3166-1 alpha-2
  currency: string; // ISO 4217
  continent: string;
}

/** Convert ISO 3166-1 alpha-2 code to flag emoji */
export function codeToFlag(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (c) => String.fromCodePoint(c.charCodeAt(0) + 127397));
}

/** Look up continent for a country code */
export function getContinent(code: string): string {
  return WORLD_COUNTRIES.find((c) => c.code === code.toUpperCase())?.continent ?? "Other";
}

export const CONTINENTS = ["Africa", "Americas", "Asia", "Europe", "Middle East", "Oceania"] as const;

export const WORLD_COUNTRIES: WorldCountry[] = [
  // ── Africa ──────────────────────────────────────────────────
  { name: "Algeria", code: "DZ", currency: "DZD", continent: "Africa" },
  { name: "Angola", code: "AO", currency: "AOA", continent: "Africa" },
  { name: "Botswana", code: "BW", currency: "BWP", continent: "Africa" },
  { name: "Cameroon", code: "CM", currency: "XAF", continent: "Africa" },
  { name: "DR Congo", code: "CD", currency: "CDF", continent: "Africa" },
  { name: "Egypt", code: "EG", currency: "EGP", continent: "Africa" },
  { name: "Ethiopia", code: "ET", currency: "ETB", continent: "Africa" },
  { name: "Ghana", code: "GH", currency: "GHS", continent: "Africa" },
  { name: "Ivory Coast", code: "CI", currency: "XOF", continent: "Africa" },
  { name: "Kenya", code: "KE", currency: "KES", continent: "Africa" },
  { name: "Libya", code: "LY", currency: "LYD", continent: "Africa" },
  { name: "Madagascar", code: "MG", currency: "MGA", continent: "Africa" },
  { name: "Malawi", code: "MW", currency: "MWK", continent: "Africa" },
  { name: "Morocco", code: "MA", currency: "MAD", continent: "Africa" },
  { name: "Mozambique", code: "MZ", currency: "MZN", continent: "Africa" },
  { name: "Namibia", code: "NA", currency: "NAD", continent: "Africa" },
  { name: "Nigeria", code: "NG", currency: "NGN", continent: "Africa" },
  { name: "Rwanda", code: "RW", currency: "RWF", continent: "Africa" },
  { name: "Senegal", code: "SN", currency: "XOF", continent: "Africa" },
  { name: "Sierra Leone", code: "SL", currency: "SLL", continent: "Africa" },
  { name: "South Africa", code: "ZA", currency: "ZAR", continent: "Africa" },
  { name: "Sudan", code: "SD", currency: "SDG", continent: "Africa" },
  { name: "Tanzania", code: "TZ", currency: "TZS", continent: "Africa" },
  { name: "Tunisia", code: "TN", currency: "TND", continent: "Africa" },
  { name: "Uganda", code: "UG", currency: "UGX", continent: "Africa" },
  { name: "Zambia", code: "ZM", currency: "ZMW", continent: "Africa" },
  { name: "Zimbabwe", code: "ZW", currency: "ZWL", continent: "Africa" },

  // ── Americas ─────────────────────────────────────────────────
  { name: "Argentina", code: "AR", currency: "ARS", continent: "Americas" },
  { name: "Bahamas", code: "BS", currency: "BSD", continent: "Americas" },
  { name: "Barbados", code: "BB", currency: "BBD", continent: "Americas" },
  { name: "Bolivia", code: "BO", currency: "BOB", continent: "Americas" },
  { name: "Brazil", code: "BR", currency: "BRL", continent: "Americas" },
  { name: "Canada", code: "CA", currency: "CAD", continent: "Americas" },
  { name: "Chile", code: "CL", currency: "CLP", continent: "Americas" },
  { name: "Colombia", code: "CO", currency: "COP", continent: "Americas" },
  { name: "Costa Rica", code: "CR", currency: "CRC", continent: "Americas" },
  { name: "Cuba", code: "CU", currency: "CUP", continent: "Americas" },
  { name: "Dominican Republic", code: "DO", currency: "DOP", continent: "Americas" },
  { name: "Ecuador", code: "EC", currency: "USD", continent: "Americas" },
  { name: "El Salvador", code: "SV", currency: "USD", continent: "Americas" },
  { name: "Guatemala", code: "GT", currency: "GTQ", continent: "Americas" },
  { name: "Guyana", code: "GY", currency: "GYD", continent: "Americas" },
  { name: "Haiti", code: "HT", currency: "HTG", continent: "Americas" },
  { name: "Honduras", code: "HN", currency: "HNL", continent: "Americas" },
  { name: "Jamaica", code: "JM", currency: "JMD", continent: "Americas" },
  { name: "Mexico", code: "MX", currency: "MXN", continent: "Americas" },
  { name: "Nicaragua", code: "NI", currency: "NIO", continent: "Americas" },
  { name: "Panama", code: "PA", currency: "USD", continent: "Americas" },
  { name: "Paraguay", code: "PY", currency: "PYG", continent: "Americas" },
  { name: "Peru", code: "PE", currency: "PEN", continent: "Americas" },
  { name: "Trinidad & Tobago", code: "TT", currency: "TTD", continent: "Americas" },
  { name: "United States", code: "US", currency: "USD", continent: "Americas" },
  { name: "Uruguay", code: "UY", currency: "UYU", continent: "Americas" },
  { name: "Venezuela", code: "VE", currency: "VES", continent: "Americas" },

  // ── Asia ─────────────────────────────────────────────────────
  { name: "Afghanistan", code: "AF", currency: "AFN", continent: "Asia" },
  { name: "Armenia", code: "AM", currency: "AMD", continent: "Asia" },
  { name: "Azerbaijan", code: "AZ", currency: "AZN", continent: "Asia" },
  { name: "Bangladesh", code: "BD", currency: "BDT", continent: "Asia" },
  { name: "Bhutan", code: "BT", currency: "BTN", continent: "Asia" },
  { name: "Brunei", code: "BN", currency: "BND", continent: "Asia" },
  { name: "Cambodia", code: "KH", currency: "KHR", continent: "Asia" },
  { name: "China", code: "CN", currency: "CNY", continent: "Asia" },
  { name: "Cyprus", code: "CY", currency: "EUR", continent: "Asia" },
  { name: "Georgia", code: "GE", currency: "GEL", continent: "Asia" },
  { name: "India", code: "IN", currency: "INR", continent: "Asia" },
  { name: "Indonesia", code: "ID", currency: "IDR", continent: "Asia" },
  { name: "Japan", code: "JP", currency: "JPY", continent: "Asia" },
  { name: "Kazakhstan", code: "KZ", currency: "KZT", continent: "Asia" },
  { name: "Kyrgyzstan", code: "KG", currency: "KGS", continent: "Asia" },
  { name: "Laos", code: "LA", currency: "LAK", continent: "Asia" },
  { name: "Malaysia", code: "MY", currency: "MYR", continent: "Asia" },
  { name: "Maldives", code: "MV", currency: "MVR", continent: "Asia" },
  { name: "Mongolia", code: "MN", currency: "MNT", continent: "Asia" },
  { name: "Myanmar", code: "MM", currency: "MMK", continent: "Asia" },
  { name: "Nepal", code: "NP", currency: "NPR", continent: "Asia" },
  { name: "Pakistan", code: "PK", currency: "PKR", continent: "Asia" },
  { name: "Philippines", code: "PH", currency: "PHP", continent: "Asia" },
  { name: "Singapore", code: "SG", currency: "SGD", continent: "Asia" },
  { name: "South Korea", code: "KR", currency: "KRW", continent: "Asia" },
  { name: "Sri Lanka", code: "LK", currency: "LKR", continent: "Asia" },
  { name: "Taiwan", code: "TW", currency: "TWD", continent: "Asia" },
  { name: "Tajikistan", code: "TJ", currency: "TJS", continent: "Asia" },
  { name: "Thailand", code: "TH", currency: "THB", continent: "Asia" },
  { name: "Timor-Leste", code: "TL", currency: "USD", continent: "Asia" },
  { name: "Turkmenistan", code: "TM", currency: "TMT", continent: "Asia" },
  { name: "Uzbekistan", code: "UZ", currency: "UZS", continent: "Asia" },
  { name: "Vietnam", code: "VN", currency: "VND", continent: "Asia" },

  // ── Europe ───────────────────────────────────────────────────
  { name: "Albania", code: "AL", currency: "ALL", continent: "Europe" },
  { name: "Austria", code: "AT", currency: "EUR", continent: "Europe" },
  { name: "Belarus", code: "BY", currency: "BYN", continent: "Europe" },
  { name: "Belgium", code: "BE", currency: "EUR", continent: "Europe" },
  { name: "Bosnia & Herzegovina", code: "BA", currency: "BAM", continent: "Europe" },
  { name: "Bulgaria", code: "BG", currency: "BGN", continent: "Europe" },
  { name: "Croatia", code: "HR", currency: "EUR", continent: "Europe" },
  { name: "Czech Republic", code: "CZ", currency: "CZK", continent: "Europe" },
  { name: "Denmark", code: "DK", currency: "DKK", continent: "Europe" },
  { name: "Estonia", code: "EE", currency: "EUR", continent: "Europe" },
  { name: "Finland", code: "FI", currency: "EUR", continent: "Europe" },
  { name: "France", code: "FR", currency: "EUR", continent: "Europe" },
  { name: "Germany", code: "DE", currency: "EUR", continent: "Europe" },
  { name: "Greece", code: "GR", currency: "EUR", continent: "Europe" },
  { name: "Hungary", code: "HU", currency: "HUF", continent: "Europe" },
  { name: "Iceland", code: "IS", currency: "ISK", continent: "Europe" },
  { name: "Ireland", code: "IE", currency: "EUR", continent: "Europe" },
  { name: "Italy", code: "IT", currency: "EUR", continent: "Europe" },
  { name: "Latvia", code: "LV", currency: "EUR", continent: "Europe" },
  { name: "Lithuania", code: "LT", currency: "EUR", continent: "Europe" },
  { name: "Luxembourg", code: "LU", currency: "EUR", continent: "Europe" },
  { name: "Malta", code: "MT", currency: "EUR", continent: "Europe" },
  { name: "Moldova", code: "MD", currency: "MDL", continent: "Europe" },
  { name: "Montenegro", code: "ME", currency: "EUR", continent: "Europe" },
  { name: "Netherlands", code: "NL", currency: "EUR", continent: "Europe" },
  { name: "North Macedonia", code: "MK", currency: "MKD", continent: "Europe" },
  { name: "Norway", code: "NO", currency: "NOK", continent: "Europe" },
  { name: "Poland", code: "PL", currency: "PLN", continent: "Europe" },
  { name: "Portugal", code: "PT", currency: "EUR", continent: "Europe" },
  { name: "Romania", code: "RO", currency: "RON", continent: "Europe" },
  { name: "Russia", code: "RU", currency: "RUB", continent: "Europe" },
  { name: "Serbia", code: "RS", currency: "RSD", continent: "Europe" },
  { name: "Slovakia", code: "SK", currency: "EUR", continent: "Europe" },
  { name: "Slovenia", code: "SI", currency: "EUR", continent: "Europe" },
  { name: "Spain", code: "ES", currency: "EUR", continent: "Europe" },
  { name: "Sweden", code: "SE", currency: "SEK", continent: "Europe" },
  { name: "Switzerland", code: "CH", currency: "CHF", continent: "Europe" },
  { name: "Turkey", code: "TR", currency: "TRY", continent: "Europe" },
  { name: "Ukraine", code: "UA", currency: "UAH", continent: "Europe" },
  { name: "United Kingdom", code: "GB", currency: "GBP", continent: "Europe" },

  // ── Middle East ──────────────────────────────────────────────
  { name: "Bahrain", code: "BH", currency: "BHD", continent: "Middle East" },
  { name: "Iran", code: "IR", currency: "IRR", continent: "Middle East" },
  { name: "Iraq", code: "IQ", currency: "IQD", continent: "Middle East" },
  { name: "Israel", code: "IL", currency: "ILS", continent: "Middle East" },
  { name: "Jordan", code: "JO", currency: "JOD", continent: "Middle East" },
  { name: "Kuwait", code: "KW", currency: "KWD", continent: "Middle East" },
  { name: "Lebanon", code: "LB", currency: "LBP", continent: "Middle East" },
  { name: "Oman", code: "OM", currency: "OMR", continent: "Middle East" },
  { name: "Palestine", code: "PS", currency: "ILS", continent: "Middle East" },
  { name: "Qatar", code: "QA", currency: "QAR", continent: "Middle East" },
  { name: "Saudi Arabia", code: "SA", currency: "SAR", continent: "Middle East" },
  { name: "Syria", code: "SY", currency: "SYP", continent: "Middle East" },
  { name: "United Arab Emirates", code: "AE", currency: "AED", continent: "Middle East" },
  { name: "Yemen", code: "YE", currency: "YER", continent: "Middle East" },

  // ── Oceania ──────────────────────────────────────────────────
  { name: "Australia", code: "AU", currency: "AUD", continent: "Oceania" },
  { name: "Fiji", code: "FJ", currency: "FJD", continent: "Oceania" },
  { name: "Kiribati", code: "KI", currency: "AUD", continent: "Oceania" },
  { name: "Marshall Islands", code: "MH", currency: "USD", continent: "Oceania" },
  { name: "Micronesia", code: "FM", currency: "USD", continent: "Oceania" },
  { name: "Nauru", code: "NR", currency: "AUD", continent: "Oceania" },
  { name: "New Zealand", code: "NZ", currency: "NZD", continent: "Oceania" },
  { name: "Palau", code: "PW", currency: "USD", continent: "Oceania" },
  { name: "Papua New Guinea", code: "PG", currency: "PGK", continent: "Oceania" },
  { name: "Samoa", code: "WS", currency: "WST", continent: "Oceania" },
  { name: "Solomon Islands", code: "SB", currency: "SBD", continent: "Oceania" },
  { name: "Tonga", code: "TO", currency: "TOP", continent: "Oceania" },
  { name: "Tuvalu", code: "TV", currency: "AUD", continent: "Oceania" },
  { name: "Vanuatu", code: "VU", currency: "VUV", continent: "Oceania" },
];